# Title: hoitenga-composers.yaml
# Author: Professor Krasso
# Date: June 7, 2023
# Modified By: Jennifer Hoitenga
# Description: Describing the Composer API
# Sources Used: 
# WEB 420 RESTful APIs assignment instructions
# Swagger API Editor: https://editor-next.swagger.io/
# YAML API Editor: https://codebeautify.org/yaml-validator

openapi: 3.0.0
info:
  title: Composer API
  version: 1.0.0
paths:
  /composers:
    get:
      summary: returns a list of composer documents
      tags:
        - Composers
      description: API for returning a list of composers from MongoDB Atlas
      responses:
        '200':
          description: Composer documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    post:
      summary: Creates a new composer object
      tags:
        - Composers
      description: API for adding new composer objects
      requestBody:
        description: Composer's Information
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - firstName
                - lastName
      responses:
        '200':
          description: User added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  /composers/{id}:
    get:
      summary: returns a composer document
      tags:
        - Composers
      description: API for returning a single composer object from MongoDB
      parameters:
        - in: path
          name: id
          description: The composerId requested by the user.
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
